imports:
    - { resource: config.yml }

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     '%env(DATABASE_HOST)%'
        dbname:   '%env(DATABASE_NAME)%'
        user:     '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASS)%'
