imports:
    - { resource: config.yml }

twig:
    cache: false

assetic:
    use_controller: false

parameters:
    env(DATABASE_HOST): "db"
    env(DATABASE_USER): "root"
    env(DATABASE_PASSWORD): "root"