<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDateArchives()
    {
        $qb = $this->_em->createQueryBuilder()
                        ->select('date')
                        ->from($this->_entityName, 'a');

        return $qb->getQuery()->getResult();
    }

    public function getFilterArticle($categoryName = null, $page = 1, $result_per_page = 5)
    {
        if (!is_numeric($page) || $page < 1)
            throw new \InvalidArgumentException('Wrong page paramter');

        $qb = $this->_em->createQueryBuilder()
                        ->select(array('a'))
                        ->from($this->_entityName, 'a')
                        ->orderBy('a.id', 'DESC')
                        ->innerJoin('a.category', 'c');
        if ($categoryName)
            $qb->where('c.name = :name')->setParameter('name', $categoryName);

        $query = $qb->getQuery()
                    ->setFirstResult($page - 1)
                    ->setMaxResults($result_per_page);

        $paginator = new Paginator($query, $fetchJoinCollection = true);

        return $paginator;
    }
}
