<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastComments($ip)
    {
        $qb = $this->_em->createQueryBuilder()
                        ->addSelect('c')
                        ->from($this->_entityName, 'c')
                        ->where('c.ip = :ip AND c.date > :last')
                        ->setParameter('ip', $ip)
                        ->setParameter('last', new \DateTime('-1 minute'), \Doctrine\DBAL\Types\Type::DATETIME);

        return $qb->getQuery()->getResult();
    }
}
