<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastContacts($ip)
    {
        $qb = $this->_em->createQueryBuilder()
            ->addSelect('c')
            ->from($this->_entityName, 'c')
            ->where('c.ip = :ip AND c.date > :last')
            ->setParameter('ip', $ip)
            ->setParameter('last', new \DateTime('-5 minute'), \Doctrine\DBAL\Types\Type::DATETIME);

        return $qb->getQuery()->getResult();
    }
}
