sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.14.0
  - REPO=toune/portfolio
  - ENV=dev

before_install:
  - docker build -t portfolio_php ./
  - docker build -t portfolio_nginx ./nginx

after_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - docker tag portfolio_php $REPO:"app-$TAG"
  - docker push $REPO:"app-$TAG"

  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      - docker tag portfolio_php $REPO:$TRAVIS_COMMIT
      - docker push $REPO:$TRAVIS_COMMIT
    fi

  - docker tag portfolio_nginx $REPO:"nginx-$TAG"
  - docker push $REPO:"nginx-$TAG"