sudo: required

services:
  - docker

env:
  - REPO=toune/portfolio

before_install:
  - export ENV=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "prod"; else echo "dev" ; fi`
  - docker build -f docker/${ENV}/Dockerfile -t portfolio_php ./
  - docker build -f docker/${ENV}/Dockerfile -t portfolio_nginx ./nginx

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - docker tag portfolio_php $REPO:"app-$TAG"
  - docker push $REPO:"app-$TAG"

  - docker tag portfolio_nginx $REPO:"nginx-$TAG"
  - docker push $REPO:"nginx-$TAG"

  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag portfolio_php $REPO:"app-${TRAVIS_COMMIT:0:6}";
    docker push $REPO:app-"${TRAVIS_COMMIT:0:6}";
    docker tag portfolio_nginx $REPO:"nginx-${TRAVIS_COMMIT:0:6}";
    docker push $REPO:nginx-"${TRAVIS_COMMIT:0:6}";
    fi