sudo: required

services:
  - docker

env:
  - REPO=toune/portfolio

before_install:
  - docker build -t portfolio_php ./
  - docker build -t portfolio_nginx ./nginx

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - docker tag portfolio_php $REPO:"app-$TAG"
  - docker push $REPO:"app-$TAG"

  - docker tag portfolio_nginx $REPO:"nginx-$TAG"
  - docker push $REPO:"nginx-$TAG"