sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.14.0
  - REPO=toune/portfolio
  - ENV=dev

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - /usr/local/bin/docker-compose up -d --force-recreate

# TODO: simple test to check nginx <--> symfony reverse proxy

after_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export PHPIMG_COMMIT_HASH=`docker-compose images -q php`

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag ${PHPIMG_COMMIT_HASH:0:11} $REPO:$TAG
  - docker push $REPO:$TAG

  - docker tag ${PHPIMG_COMMIT_HASH:0:11} $REPO:$TRAVIS_COMMIT
  - docker push $REPO:$TRAVIS_COMMIT
