version: '2'

services:
    db:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=symfony
        - MYSQL_PASSWORD=symfony
      volumes:
        - ./db:/var/lib/mysql
    app:
      build: .
      volumes:
        - ./app:/app
      ports:
        - 80:80
