version: '2'

services:
    db:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=symfony
        - MYSQL_USER=symfony
        - MYSQL_PASSWORD=symfony
      volumes:
        - ./db:/var/lib/mysql
    app:
      build:
        context: docker/dev
      volumes:
        - ./app:/www
      environment:
        - DATABASE_HOST=db
        - DATABASE_NAME=symfony
        - DATABASE_USER=symfony
        - DATABASE_PASS=symfony
      ports:
        - 80:80
