app:
    resource: '@AppBundle/Controller/'
    type: annotation

blog:
    resource: '@AppBundle/Controller/Blog'
    type: annotation
    prefix: /blog

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /user