<?php

namespace AppBundle\Repository;

/**
 * ProjectTechnologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTechnologyRepository extends \Doctrine\ORM\EntityRepository
{
}
