<?php

namespace AppBundle\Repository;

/**
 * ProjectLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
